// Stock Windows font baseline + the curated probe dictionary for host-font leak
// detection. Generated from the HKLM font registry of a clean Windows 10
// Enterprise LTSC 2021 (10.0.19044) box on 2026-06-25, confirmed against the
// measureText width-probe. Provenance + live validation:
// scripts/verify-windows/windows-font-baseline.json.
//
// Threat model: queryLocalFonts() is blocked (local_fonts: 2), so a fingerprinter
// is limited to the measureText width-probe over font names it already knows. We
// mirror that adversary: probe WINDOWS_FONT_BASELINE ∪ NON_STOCK_FONTS and flag any
// detected family outside the stock baseline. Arbitrary custom font names not in
// the dictionary are invisible to the adversary and to us alike. "Helvetica" is in
// the baseline because Windows GDI aliases it to Arial on every box (probe artifact).

/** Stock families a default Windows 10/11 install exposes (HKLM, normalized). */
export const WINDOWS_FONT_BASELINE: string[] = [
  "Arial",
  "Arial Black",
  "Arial Bold",
  "Arial Bold Italic",
  "Arial Italic",
  "Bahnschrift",
  "Calibri",
  "Calibri Bold",
  "Calibri Bold Italic",
  "Calibri Italic",
  "Calibri Light",
  "Calibri Light Italic",
  "Cambria",
  "Cambria Bold",
  "Cambria Bold Italic",
  "Cambria Italic",
  "Candara",
  "Candara Bold",
  "Candara Bold Italic",
  "Candara Italic",
  "Candara Light",
  "Candara Light Italic",
  "Comic Sans MS",
  "Comic Sans MS Bold",
  "Comic Sans MS Bold Italic",
  "Comic Sans MS Italic",
  "Consolas",
  "Consolas Bold",
  "Consolas Bold Italic",
  "Consolas Italic",
  "Constantia",
  "Constantia Bold",
  "Constantia Bold Italic",
  "Constantia Italic",
  "Corbel",
  "Corbel Bold",
  "Corbel Bold Italic",
  "Corbel Italic",
  "Corbel Light",
  "Corbel Light Italic",
  "Courier 10,12,15",
  "Courier 10,12,15 (120)",
  "Courier New",
  "Courier New Bold",
  "Courier New Bold Italic",
  "Courier New Italic",
  "Ebrima",
  "Ebrima Bold",
  "Franklin Gothic",
  "Franklin Gothic Medium",
  "Franklin Gothic Medium Italic",
  "Gabriola",
  "Gadugi",
  "Gadugi Bold",
  "Georgia",
  "Georgia Bold",
  "Georgia Bold Italic",
  "Georgia Italic",
  "Helvetica",
  "Impact",
  "Ink Free",
  "Javanese Text",
  "Leelawadee UI",
  "Leelawadee UI Bold",
  "Leelawadee UI Semilight",
  "Lucida Console",
  "Lucida Sans Unicode",
  "MS Gothic",
  "MS Sans Serif 8,10,12,14,18,24",
  "MS Sans Serif 8,10,12,14,18,24 (120)",
  "MS Serif 8,10,12,14,18,24",
  "MS Serif 8,10,12,14,18,24 (120)",
  "MV Boli",
  "Malgun Gothic",
  "Malgun Gothic Bold",
  "Malgun Gothic SemiLight",
  "Microsoft Himalaya",
  "Microsoft JhengHei",
  "Microsoft JhengHei Bold",
  "Microsoft JhengHei Light",
  "Microsoft New Tai Lue",
  "Microsoft New Tai Lue Bold",
  "Microsoft PhagsPa",
  "Microsoft PhagsPa Bold",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft Tai Le Bold",
  "Microsoft YaHei",
  "Microsoft YaHei Bold",
  "Microsoft YaHei Light",
  "Microsoft Yi Baiti",
  "MingLiU-ExtB",
  "Modern",
  "Mongolian Baiti",
  "Myanmar Text",
  "Myanmar Text Bold",
  "Nirmala UI",
  "Nirmala UI Bold",
  "Nirmala UI Semilight",
  "Palatino Linotype",
  "Palatino Linotype Bold",
  "Palatino Linotype Bold Italic",
  "Palatino Linotype Italic",
  "Roman",
  "Script",
  "Segoe MDL2 Assets",
  "Segoe Print",
  "Segoe Print Bold",
  "Segoe Script",
  "Segoe Script Bold",
  "Segoe UI",
  "Segoe UI Black",
  "Segoe UI Black Italic",
  "Segoe UI Bold",
  "Segoe UI Bold Italic",
  "Segoe UI Emoji",
  "Segoe UI Historic",
  "Segoe UI Italic",
  "Segoe UI Light",
  "Segoe UI Light Italic",
  "Segoe UI Semibold",
  "Segoe UI Semibold Italic",
  "Segoe UI Semilight",
  "Segoe UI Semilight Italic",
  "Segoe UI Symbol",
  "SimSun",
  "SimSun-ExtB",
  "SimSun-ExtG",
  "Sitka Small",
  "Sitka Small Bold",
  "Sitka Small Bold Italic",
  "Sitka Small Italic",
  "Small Fonts",
  "Small Fonts (120)",
  "Sylfaen",
  "Symbol",
  "Tahoma",
  "Tahoma Bold",
  "Times New Roman",
  "Times New Roman Bold",
  "Times New Roman Bold Italic",
  "Times New Roman Italic",
  "Trebuchet MS",
  "Trebuchet MS Bold",
  "Trebuchet MS Bold Italic",
  "Trebuchet MS Italic",
  "Verdana",
  "Verdana Bold",
  "Verdana Bold Italic",
  "Verdana Italic",
  "Webdings",
  "Wingdings",
  "Yu Gothic",
  "Yu Gothic Bold",
  "Yu Gothic Light",
  "Yu Gothic Medium",
  "Yu Gothic Regular",
];

/** Non-stock families a fingerprinter commonly tests. Disjoint from the baseline. */
export const NON_STOCK_FONTS: string[] = [
  "Adobe Clean",
  "Anonymous Pro",
  "Avenir",
  "Avenir Next",
  "Cantarell",
  "Cascadia Code",
  "Cascadia Mono",
  "DejaVu Sans",
  "DejaVu Sans Mono",
  "DejaVu Serif",
  "Droid Sans",
  "Fira Code",
  "Fira Sans",
  "FiraCode",
  "FreeMono",
  "FreeSans",
  "FreeSerif",
  "Geneva",
  "Hack",
  "Helvetica Neue",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "Inconsolata",
  "Inter",
  "JetBrains Mono",
  "Lato",
  "Liberation Mono",
  "Liberation Sans",
  "Liberation Serif",
  "Lucida Grande",
  "Menlo",
  "Merriweather",
  "Minion Pro",
  "Monaco",
  "Montserrat",
  "Myriad Pro",
  "Noto Color Emoji",
  "Noto Mono",
  "Noto Sans",
  "Noto Serif",
  "Nunito",
  "Nunito Sans",
  "Open Sans",
  "Oswald",
  "PT Mono",
  "PT Sans",
  "Poppins",
  "Raleway",
  "Roboto",
  "Roboto Condensed",
  "Roboto Mono",
  "SF Mono",
  "SF Pro Display",
  "SF Pro Text",
  "San Francisco",
  "Source Code Pro",
  "Source Han Sans",
  "Source Sans 3",
  "Source Sans Pro",
  "Source Serif Pro",
  "Ubuntu",
  "Ubuntu Condensed",
  "Ubuntu Mono",
  "Work Sans",
];

/** What the in-page width-probe enumerates = baseline ∪ non-stock. */
export const FONT_DICTIONARY: string[] = [
  "Adobe Clean",
  "Anonymous Pro",
  "Arial",
  "Arial Black",
  "Arial Bold",
  "Arial Bold Italic",
  "Arial Italic",
  "Avenir",
  "Avenir Next",
  "Bahnschrift",
  "Calibri",
  "Calibri Bold",
  "Calibri Bold Italic",
  "Calibri Italic",
  "Calibri Light",
  "Calibri Light Italic",
  "Cambria",
  "Cambria Bold",
  "Cambria Bold Italic",
  "Cambria Italic",
  "Candara",
  "Candara Bold",
  "Candara Bold Italic",
  "Candara Italic",
  "Candara Light",
  "Candara Light Italic",
  "Cantarell",
  "Cascadia Code",
  "Cascadia Mono",
  "Comic Sans MS",
  "Comic Sans MS Bold",
  "Comic Sans MS Bold Italic",
  "Comic Sans MS Italic",
  "Consolas",
  "Consolas Bold",
  "Consolas Bold Italic",
  "Consolas Italic",
  "Constantia",
  "Constantia Bold",
  "Constantia Bold Italic",
  "Constantia Italic",
  "Corbel",
  "Corbel Bold",
  "Corbel Bold Italic",
  "Corbel Italic",
  "Corbel Light",
  "Corbel Light Italic",
  "Courier 10,12,15",
  "Courier 10,12,15 (120)",
  "Courier New",
  "Courier New Bold",
  "Courier New Bold Italic",
  "Courier New Italic",
  "DejaVu Sans",
  "DejaVu Sans Mono",
  "DejaVu Serif",
  "Droid Sans",
  "Ebrima",
  "Ebrima Bold",
  "Fira Code",
  "Fira Sans",
  "FiraCode",
  "Franklin Gothic",
  "Franklin Gothic Medium",
  "Franklin Gothic Medium Italic",
  "FreeMono",
  "FreeSans",
  "FreeSerif",
  "Gabriola",
  "Gadugi",
  "Gadugi Bold",
  "Geneva",
  "Georgia",
  "Georgia Bold",
  "Georgia Bold Italic",
  "Georgia Italic",
  "Hack",
  "Helvetica",
  "Helvetica Neue",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "Impact",
  "Inconsolata",
  "Ink Free",
  "Inter",
  "Javanese Text",
  "JetBrains Mono",
  "Lato",
  "Leelawadee UI",
  "Leelawadee UI Bold",
  "Leelawadee UI Semilight",
  "Liberation Mono",
  "Liberation Sans",
  "Liberation Serif",
  "Lucida Console",
  "Lucida Grande",
  "Lucida Sans Unicode",
  "MS Gothic",
  "MS Sans Serif 8,10,12,14,18,24",
  "MS Sans Serif 8,10,12,14,18,24 (120)",
  "MS Serif 8,10,12,14,18,24",
  "MS Serif 8,10,12,14,18,24 (120)",
  "MV Boli",
  "Malgun Gothic",
  "Malgun Gothic Bold",
  "Malgun Gothic SemiLight",
  "Menlo",
  "Merriweather",
  "Microsoft Himalaya",
  "Microsoft JhengHei",
  "Microsoft JhengHei Bold",
  "Microsoft JhengHei Light",
  "Microsoft New Tai Lue",
  "Microsoft New Tai Lue Bold",
  "Microsoft PhagsPa",
  "Microsoft PhagsPa Bold",
  "Microsoft Sans Serif",
  "Microsoft Tai Le",
  "Microsoft Tai Le Bold",
  "Microsoft YaHei",
  "Microsoft YaHei Bold",
  "Microsoft YaHei Light",
  "Microsoft Yi Baiti",
  "MingLiU-ExtB",
  "Minion Pro",
  "Modern",
  "Monaco",
  "Mongolian Baiti",
  "Montserrat",
  "Myanmar Text",
  "Myanmar Text Bold",
  "Myriad Pro",
  "Nirmala UI",
  "Nirmala UI Bold",
  "Nirmala UI Semilight",
  "Noto Color Emoji",
  "Noto Mono",
  "Noto Sans",
  "Noto Serif",
  "Nunito",
  "Nunito Sans",
  "Open Sans",
  "Oswald",
  "PT Mono",
  "PT Sans",
  "Palatino Linotype",
  "Palatino Linotype Bold",
  "Palatino Linotype Bold Italic",
  "Palatino Linotype Italic",
  "Poppins",
  "Raleway",
  "Roboto",
  "Roboto Condensed",
  "Roboto Mono",
  "Roman",
  "SF Mono",
  "SF Pro Display",
  "SF Pro Text",
  "San Francisco",
  "Script",
  "Segoe MDL2 Assets",
  "Segoe Print",
  "Segoe Print Bold",
  "Segoe Script",
  "Segoe Script Bold",
  "Segoe UI",
  "Segoe UI Black",
  "Segoe UI Black Italic",
  "Segoe UI Bold",
  "Segoe UI Bold Italic",
  "Segoe UI Emoji",
  "Segoe UI Historic",
  "Segoe UI Italic",
  "Segoe UI Light",
  "Segoe UI Light Italic",
  "Segoe UI Semibold",
  "Segoe UI Semibold Italic",
  "Segoe UI Semilight",
  "Segoe UI Semilight Italic",
  "Segoe UI Symbol",
  "SimSun",
  "SimSun-ExtB",
  "SimSun-ExtG",
  "Sitka Small",
  "Sitka Small Bold",
  "Sitka Small Bold Italic",
  "Sitka Small Italic",
  "Small Fonts",
  "Small Fonts (120)",
  "Source Code Pro",
  "Source Han Sans",
  "Source Sans 3",
  "Source Sans Pro",
  "Source Serif Pro",
  "Sylfaen",
  "Symbol",
  "Tahoma",
  "Tahoma Bold",
  "Times New Roman",
  "Times New Roman Bold",
  "Times New Roman Bold Italic",
  "Times New Roman Italic",
  "Trebuchet MS",
  "Trebuchet MS Bold",
  "Trebuchet MS Bold Italic",
  "Trebuchet MS Italic",
  "Ubuntu",
  "Ubuntu Condensed",
  "Ubuntu Mono",
  "Verdana",
  "Verdana Bold",
  "Verdana Bold Italic",
  "Verdana Italic",
  "Webdings",
  "Wingdings",
  "Work Sans",
  "Yu Gothic",
  "Yu Gothic Bold",
  "Yu Gothic Light",
  "Yu Gothic Medium",
  "Yu Gothic Regular",
];
